### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by XiSheng1998** [IllinoisRocstar/Rocstar#2] opened 2019-10-30 13:52 UTC
I tried to install this Rocstar version, Since there's no com.h file in $IMPACT_INSTALL_PATH/include, I changed settings of cmake prefix, change
```
-DIMPACT_HDR=$IMPACT_INSTALL_PATH/include/com.h
```
to 
```
-DIMPACT_HDR=$IMPACT_INSTALL_PATH/include/impact/com.h
```
and cmake process works successfully. but make -j process keeps outputting errors, and make terminal no response. I've sent the ccmake screenshot, "make" log and some more detail to msafdari@illinoisrocstar.com.

**Comment by msafdari1234** [comment] 2019-10-30 17:57
First,
-DIMPACT_HDR=$IMPACT_INSTALL_PATH/include/com.h  is correct syntax, just make sure "$IMPACT_INSTALL_PATH/include" translates to the right installation path.

Second
To keep terminal responsive "make -jn" where n is the number of cores on your system

Keep in mind Rocstar is not tested with latest compilers yet, so if you face build problems always include your compiler information.

**Comment by XiSheng1998** [comment] 2019-10-31 05:20
> First,
> -DIMPACT_HDR=$IMPACT_INSTALL_PATH/include/com.h  is correct syntax, just make sure "$IMPACT_INSTALL_PATH/include" translates to the right installation path.
> Second
> To keep terminal responsive "make -jn" where n is the number of cores on your system
> Keep in mind Rocstar is not tested with latest compilers yet, so if you face build problems always include your compiler information.

CXX, C and Fortran compiler is GNU 7.4.0, MPI version is 3.1, doxygen version is 1.8.13. Actually I tried the original command by copying the command from GitHub, here $METIS_INC_PATH=../metis/Lib, $METIS_LIB_PATH=../metis/libmetis.a.
```
root@ubuntu:/usr/local/src/Rocstar-IMPACT/build# cmake -DCMAKE_INSTALL_PREFIX=$ROCSTAR_INSTALL_PATH -DENABLE_MPI=ON -DENABLE_CGNS=ON -DIMPACT_HDR=$IMPACT_INSTALL_PATH/include/com.h -DMETIS_INC=$METIS_INC_PATH -DMETIS_LIB=$METIS_LIB_PATH -DSITCOM_LIB=$IMPACT_INSTALL_PATH/lib/libSITCOM.so ..
-- The CXX compiler identification is GNU 7.4.0
-- The C compiler identification is GNU 7.4.0
-- The Fortran compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/libmpich.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/libmpichcxx.so (found version "3.1") 
-- Found MPI_Fortran: /usr/lib/x86_64-linux-gnu/libmpichfort.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- No build type selected, default to Release
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.0.1")  
-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- A library with BLAS API found.
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen missing components:  dot
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/Rocstar-IMPACT/build
```
however make -j4 cracks quicker:
```
root@ubuntu:/usr/local/src/Rocstar-IMPACT/build# make -j4
Scanning dependencies of target Rocprop
Scanning dependencies of target Rocon
Scanning dependencies of target Rocman
Scanning dependencies of target mesquite_95
[  0%] Building CXX object Rocprop/CMakeFiles/Rocprop.dir/src/Propagation_3.C.o
[  0%] Building CXX object Rocmop/External/mesquite_0_9_5/CMakeFiles/mesquite_95.dir/srcLinks/ASMQualityMetric.cpp.o
[  1%] Building CXX object Rocman/CMakeFiles/Rocman.dir/src/rocstar_driver.C.o
[  1%] Building CXX object Rocon/CMakeFiles/Rocon.dir/src/Rocon.C.o
cc1plus: warning: /opt/IMPACT/include/com.h: not a directory
/usr/local/src/Rocstar-IMPACT/Rocmop/External/mesquite_0_9_5/srcLinks/ASMQualityMetric.cpp:1:1: error: expected unqualified-id before ‘.’ token
 ../src/QualityMetric/Smoothness/ASMQualityMetric.cpp
 ^
Rocmop/External/mesquite_0_9_5/CMakeFiles/mesquite_95.dir/build.make:62: recipe for target 'Rocmop/External/mesquite_0_9_5/CMakeFiles/mesquite_95.dir/srcLinks/ASMQualityMetric.cpp.o' failed
make[2]: *** [Rocmop/External/mesquite_0_9_5/CMakeFiles/mesquite_95.dir/srcLinks/ASMQualityMetric.cpp.o] Error 1
CMakeFiles/Makefile2:1596: recipe for target 'Rocmop/External/mesquite_0_9_5/CMakeFiles/mesquite_95.dir/all' failed
make[1]: *** [Rocmop/External/mesquite_0_9_5/CMakeFiles/mesquite_95.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  1%] Building CXX object Rocon/CMakeFiles/Rocon.dir/src/ray-triangle.C.o
In file included from /usr/include/c++/7/ext/hash_map:60:0,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/BndSurface.h:7,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/Rocon.H:59,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/src/Rocon.C:6:
/usr/include/c++/7/backward/backward_warning.h:32:2: warning: #warning This file includes at least one deprecated or antiquated header which may be removed without further notice at a future date. Please use a non-deprecated interface with equivalent functionality instead. For a listing of replacement headers and interfaces, consult the file backward_warning.h. To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning \
  ^~~~~~~
In file included from /usr/local/src/Rocstar-IMPACT/Rocon/include/PMesh.H:36:0,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/TRAIL.H:25,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/src/Rocon.C:7:
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H: In member function ‘int IRAD::Comm::CommunicatorObject::GatherMO(std::vector<Object>&, std::vector<Object>&, std::vector<int>&, int)’:
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H:482:12: error: no match for ‘operator+=’ (operand types are ‘int’ and ‘__gnu_cxx::__normal_iterator<int*, std::vector<int> >’)
      nrecv += nsi++;
      ~~~~~~^~~~~~~~
In file included from /usr/local/src/Rocstar-IMPACT/Rocon/include/triangle.h:5:0,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/BndSurface.h:12,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/Rocon.H:59,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/src/Rocon.C:6:
/usr/local/src/Rocstar-IMPACT/Rocon/include/NVec.h:113:24: note: candidate: template<int DIM, class T> nvc::NVec<DIM, T> nvc::operator+=(nvc::NVec<DIM, T>&, const nvc::NVec<DIM, T>&)
     inline NVec<DIM,T> operator+=(NVec<DIM,T> &u, const NVec<DIM,T>& v)
                        ^~~~~~~~
/usr/local/src/Rocstar-IMPACT/Rocon/include/NVec.h:113:24: note:   template argument deduction/substitution failed:
In file included from /usr/local/src/Rocstar-IMPACT/Rocon/include/PMesh.H:36:0,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/TRAIL.H:25,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/src/Rocon.C:7:
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H:482:18: note:   mismatched types ‘nvc::NVec<DIM, T>’ and ‘int’
      nrecv += nsi++;
                  ^~
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H: In member function ‘int IRAD::Comm::CommunicatorObject::AllGatherMO(std::vector<Object>&, std::vector<Object>&, std::vector<int>&, int)’:
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H:529:12: error: no match for ‘operator+=’ (operand types are ‘int’ and ‘__gnu_cxx::__normal_iterator<int*, std::vector<int> >’)
      nrecv += nsi++;
      ~~~~~~^~~~~~~~
In file included from /usr/local/src/Rocstar-IMPACT/Rocon/include/triangle.h:5:0,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/BndSurface.h:12,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/Rocon.H:59,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/src/Rocon.C:6:
/usr/local/src/Rocstar-IMPACT/Rocon/include/NVec.h:113:24: note: candidate: template<int DIM, class T> nvc::NVec<DIM, T> nvc::operator+=(nvc::NVec<DIM, T>&, const nvc::NVec<DIM, T>&)
     inline NVec<DIM,T> operator+=(NVec<DIM,T> &u, const NVec<DIM,T>& v)
                        ^~~~~~~~
/usr/local/src/Rocstar-IMPACT/Rocon/include/NVec.h:113:24: note:   template argument deduction/substitution failed:
In file included from /usr/local/src/Rocstar-IMPACT/Rocon/include/PMesh.H:36:0,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/TRAIL.H:25,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/src/Rocon.C:7:
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H:529:18: note:   mismatched types ‘nvc::NVec<DIM, T>’ and ‘int’
      nrecv += nsi++;
                  ^~
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H: In member function ‘int IRAD::Comm::CommunicatorObject::GatherMOV(std::vector<Object>&, std::vector<Object>&, std::vector<int>&, int)’:
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H:561:12: error: no match for ‘operator+=’ (operand types are ‘int’ and ‘__gnu_cxx::__normal_iterator<int*, std::vector<int> >’)
      nrecv += nsi++;
      ~~~~~~^~~~~~~~
In file included from /usr/local/src/Rocstar-IMPACT/Rocon/include/triangle.h:5:0,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/BndSurface.h:12,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/Rocon.H:59,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/src/Rocon.C:6:
/usr/local/src/Rocstar-IMPACT/Rocon/include/NVec.h:113:24: note: candidate: template<int DIM, class T> nvc::NVec<DIM, T> nvc::operator+=(nvc::NVec<DIM, T>&, const nvc::NVec<DIM, T>&)
     inline NVec<DIM,T> operator+=(NVec<DIM,T> &u, const NVec<DIM,T>& v)
                        ^~~~~~~~
/usr/local/src/Rocstar-IMPACT/Rocon/include/NVec.h:113:24: note:   template argument deduction/substitution failed:
In file included from /usr/local/src/Rocstar-IMPACT/Rocon/include/PMesh.H:36:0,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/TRAIL.H:25,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/src/Rocon.C:7:
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H:561:18: note:   mismatched types ‘nvc::NVec<DIM, T>’ and ‘int’
      nrecv += nsi++;
                  ^~
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H: In member function ‘int IRAD::Comm::CommunicatorObject::AllGatherMOV(std::vector<Object>&, std::vector<Object>&, std::vector<int>&, int)’:
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H:593:12: error: no match for ‘operator+=’ (operand types are ‘int’ and ‘__gnu_cxx::__normal_iterator<int*, std::vector<int> >’)
      nrecv += nsi++;
      ~~~~~~^~~~~~~~
/usr/local/src/Rocstar-IMPACT/Rocman/src/rocstar_driver.C: In function ‘double get_restart_time(const string&)’:
/usr/local/src/Rocstar-IMPACT/Rocman/src/rocstar_driver.C:88:13: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
       fscanf(fp, "%d %le", &curStep, &curTime);
       ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/src/Rocstar-IMPACT/Rocon/include/triangle.h:5:0,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/BndSurface.h:12,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/Rocon.H:59,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/src/Rocon.C:6:
/usr/local/src/Rocstar-IMPACT/Rocon/include/NVec.h:113:24: note: candidate: template<int DIM, class T> nvc::NVec<DIM, T> nvc::operator+=(nvc::NVec<DIM, T>&, const nvc::NVec<DIM, T>&)
     inline NVec<DIM,T> operator+=(NVec<DIM,T> &u, const NVec<DIM,T>& v)
                        ^~~~~~~~
/usr/local/src/Rocstar-IMPACT/Rocon/include/NVec.h:113:24: note:   template argument deduction/substitution failed:
In file included from /usr/local/src/Rocstar-IMPACT/Rocon/include/PMesh.H:36:0,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/TRAIL.H:25,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/src/Rocon.C:7:
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H:593:18: note:   mismatched types ‘nvc::NVec<DIM, T>’ and ‘int’
      nrecv += nsi++;
                  ^~
[  1%] Building CXX object Rocon/CMakeFiles/Rocon.dir/src/GEM.C.o
Rocon/CMakeFiles/Rocon.dir/build.make:62: recipe for target 'Rocon/CMakeFiles/Rocon.dir/src/Rocon.C.o' failed
make[2]: *** [Rocon/CMakeFiles/Rocon.dir/src/Rocon.C.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  1%] Building CXX object Rocman/CMakeFiles/Rocman.dir/src/Action.C.o
cc1plus: warning: /opt/IMPACT/include/com.h: not a directory
In file included from /usr/local/src/Rocstar-IMPACT/Rocon/include/PMesh.H:36:0,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/include/TRAIL.H:25,
                 from /usr/local/src/Rocstar-IMPACT/Rocon/src/GEM.C:39:
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H: In member function ‘int IRAD::Comm::CommunicatorObject::GatherMO(std::vector<T>&, std::vector<T>&, std::vector<int>&, int)’:
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H:482:12: error: no match for ‘operator+=’ (operand types are ‘int’ and ‘__gnu_cxx::__normal_iterator<int*, std::vector<int> >’)
      nrecv += nsi++;
      ~~~~~~^~~~~~~~
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H: In member function ‘int IRAD::Comm::CommunicatorObject::AllGatherMO(std::vector<T>&, std::vector<T>&, std::vector<int>&, int)’:
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H:529:12: error: no match for ‘operator+=’ (operand types are ‘int’ and ‘__gnu_cxx::__normal_iterator<int*, std::vector<int> >’)
      nrecv += nsi++;
      ~~~~~~^~~~~~~~
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H: In member function ‘int IRAD::Comm::CommunicatorObject::GatherMOV(std::vector<T>&, std::vector<T>&, std::vector<int>&, int)’:
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H:561:12: error: no match for ‘operator+=’ (operand types are ‘int’ and ‘__gnu_cxx::__normal_iterator<int*, std::vector<int> >’)
      nrecv += nsi++;
      ~~~~~~^~~~~~~~
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H: In member function ‘int IRAD::Comm::CommunicatorObject::AllGatherMOV(std::vector<T>&, std::vector<T>&, std::vector<int>&, int)’:
/usr/local/src/Rocstar-IMPACT/Rocon/include/COMM.H:593:12: error: no match for ‘operator+=’ (operand types are ‘int’ and ‘__gnu_cxx::__normal_iterator<int*, std::vector<int> >’)
      nrecv += nsi++;
      ~~~~~~^~~~~~~~
[  1%] Building CXX object Rocprop/CMakeFiles/Rocprop.dir/src/MarkerParticles_3.C.o
[  1%] Building CXX object Rocman/CMakeFiles/Rocman.dir/src/Scheduler.C.o
cc1plus: warning: /opt/IMPACT/include/com.h: not a directory
[  1%] Building CXX object Rocman/CMakeFiles/Rocman.dir/src/Coupling.C.o
cc1plus: warning: /opt/IMPACT/include/com.h: not a directory
Rocon/CMakeFiles/Rocon.dir/build.make:110: recipe for target 'Rocon/CMakeFiles/Rocon.dir/src/GEM.C.o' failed
make[2]: *** [Rocon/CMakeFiles/Rocon.dir/src/GEM.C.o] Error 1
CMakeFiles/Makefile2:1694: recipe for target 'Rocon/CMakeFiles/Rocon.dir/all' failed
make[1]: *** [Rocon/CMakeFiles/Rocon.dir/all] Error 2
[  1%] Building CXX object Rocman/CMakeFiles/Rocman.dir/src/Agent.C.o
cc1plus: warning: /opt/IMPACT/include/com.h: not a directory
[  1%] Building CXX object Rocprop/CMakeFiles/Rocprop.dir/src/FaceOffset_3.C.o
/usr/local/src/Rocstar-IMPACT/Rocman/src/Coupling.C: In member function ‘void Coupling::read_restart_info()’:
/usr/local/src/Rocstar-IMPACT/Rocman/src/Coupling.C:324:13: warning: ignoring return value of ‘int fscanf(FILE*, const char*, ...)’, declared with attribute warn_unused_result [-Wunused-result]
       fscanf(fp, "%d %le", &curStep, &initialTime);
       ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  1%] Building CXX object Rocman/CMakeFiles/Rocman.dir/src/SolidAgent.C.o
cc1plus: warning: /opt/IMPACT/include/com.h: not a directory
[  1%] Building CXX object Rocman/CMakeFiles/Rocman.dir/src/BurnAgent.C.o
cc1plus: warning: /opt/IMPACT/include/com.h: not a directory
[  1%] Building CXX object Rocprop/CMakeFiles/Rocprop.dir/src/Rocprop.C.o
[  1%] Building CXX object Rocman/CMakeFiles/Rocman.dir/src/basic_actions.C.o
cc1plus: warning: /opt/IMPACT/include/com.h: not a directory
[  1%] Building CXX object Rocman/CMakeFiles/Rocman.dir/src/transfer_actions.C.o
cc1plus: warning: /opt/IMPACT/include/com.h: not a directory
[  2%] Building CXX object Rocman/CMakeFiles/Rocman.dir/src/Interpolate.C.o
cc1plus: warning: /opt/IMPACT/include/com.h: not a directory
[  2%] Building CXX object Rocprop/CMakeFiles/Rocprop.dir/src/NuLaplacian.C.o
[  2%] Building CXX object Rocman/CMakeFiles/Rocman.dir/src/builtin_couplings.C.o
cc1plus: warning: /opt/IMPACT/include/com.h: not a directory
[  2%] Building CXX object Rocprop/CMakeFiles/Rocprop.dir/src/cons_diff.C.o
[  2%] Building CXX object Rocman/CMakeFiles/Rocman.dir/src/derived_couplings.C.o
cc1plus: warning: /opt/IMPACT/include/com.h: not a directory
[  2%] Building CXX object Rocman/CMakeFiles/Rocman.dir/src/Surfdiver.C.o
cc1plus: warning: /opt/IMPACT/include/com.h: not a directory
[  2%] Building CXX object Rocprop/CMakeFiles/Rocprop.dir/src/AnisotropicSmoothing.C.o
[  2%] Building CXX object Rocman/CMakeFiles/Rocman.dir/src/FluidAgent.C.o
cc1plus: warning: /opt/IMPACT/include/com.h: not a directory
[  3%] Building CXX object Rocprop/CMakeFiles/Rocprop.dir/src/quadric_analysis.C.o
[  3%] Building CXX object Rocprop/CMakeFiles/Rocprop.dir/src/detect_features.C.o
[  3%] Linking CXX shared library ../lib/libRocman.so
[  3%] Built target Rocman
[  3%] Linking CXX shared library ../lib/libRocprop.so
[  3%] Built target Rocprop
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by msafdari1234** [comment] 2019-10-31 16:45
The issue is confirmed. Rocstar is currently under major improvement. Withing a few weeks we will release the patches that will address issues such as this. Please be patient.

**Comment by XiSheng1998** [comment] 2019-11-11 02:39
> The issue is confirmed. Rocstar is currently under major improvement. Withing a few weeks we will release the patches that will address issues such as this. Please be patient.

OK, waiting for patches, thanks.

**Comment by XiSheng1998** [comment] 2019-11-17 02:37
I'm wondering if the issue is fixed, and I'm looking forward to the lastest release, thanks.

**Comment by msafdari1234** [comment] 2019-11-17 16:07
We are still developing and testing the improved code. It should be ready for release soon.

**Comment by MartiRubio** [comment] 2019-11-30 12:43
Hi, I have just reproduced the error in a Ubuntu Bash inside Windows. 

Do you know how long will it take for the fix to be live?

**Comment by XiSheng1998** [comment] 2019-12-23 05:30
Just come to see if the issue was fixed, and still looking forward to the latest release.

**Comment by msafdari1234** [comment] 2020-04-02 18:22
Issue is fixed now. Go ahead and try. Several updates are made to the project.

**Closed as completed** 2020-04-02 18:22 UTC
